/**
 * TAPS-4.5: splits a `PastPaper.extractedText` into page-boundary-aware
 * chunks before it's sent to an AI provider, and dedupes the resulting
 * per-chunk `QuizQuestion` candidates before persistence.
 *
 * See `docs/adr/025-quiz-generation-paper-chunking.md` for the root cause
 * (`gpt-5.6-terra`'s hidden reasoning tokens exhaust the fixed
 * `max_completion_tokens` budget on a full-size paper before any visible
 * output is emitted — `finish_reason: length`, empty content) and why this
 * page-count-based approach was chosen over Part/section detection or a
 * blind `max_completion_tokens` increase.
 */

/** One page of `pdf-parse`'s extracted text, marker stripped. */
export interface ExtractedPage {
  num: number;
  total: number;
  text: string;
}

/**
 * `pdf-parse`'s default page joiner (`ParseParameters.ts`'s
 * `'\n-- page_number of total_number --'`, confirmed against the installed
 * package — `PastPaperIngestionService` calls `parser.getText()` with no
 * override, so every `PastPaper.extractedText` in this codebase carries
 * this exact marker between pages, e.g. `-- 34 of 48 --`, as the 2026-09-13
 * audit documented).
 */
const PAGE_MARKER_RE = /\n-- (\d+) of (\d+) --\n\n/g;

/**
 * Parses `extractedText` back into its per-page pieces using the
 * `-- N of M --` markers `pdf-parse` inserts. Text with no such marker at
 * all (a short/plain-text paper, or a test fixture) is treated as a single
 * page — this is what keeps `chunkPastPaperText` a no-op for anything that
 * already fits in one chunk today.
 */
export function splitIntoPages(extractedText: string): ExtractedPage[] {
  const pages: ExtractedPage[] = [];
  const re = new RegExp(PAGE_MARKER_RE.source, 'g');
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = re.exec(extractedText)) !== null) {
    pages.push({
      num: Number(match[1]),
      total: Number(match[2]),
      text: extractedText.slice(lastIndex, match.index),
    });
    lastIndex = re.lastIndex;
  }

  if (pages.length === 0) {
    return [{ num: 1, total: 1, text: extractedText }];
  }

  const trailing = extractedText.slice(lastIndex);
  if (trailing.trim().length > 0) {
    // Unexpected content after the final marker — keep it rather than
    // silently drop it, rather than assume the marker format above is the
    // only thing that can ever follow the last page.
    pages[pages.length - 1].text += '\n\n' + trailing;
  }
  return pages;
}

/**
 * Chosen from the one real data point this story has: a ~30-question slice
 * of `PastPaper cmtyqyy0z0001sahpuyhz0v24` (see `docs/backlog/BACKLOG.md`'s
 * `TAPS-4.5` row) completed cleanly at 3,125 completion tokens against the
 * 8,192 cap, while the full ~150-190-question, 48-page paper exhausted the
 * whole cap on hidden reasoning tokens before any visible output. That
 * paper's ~150-190 questions over 48 pages is ~3.1-4.0 questions/page, so 8
 * pages/chunk lands at roughly 25-32 questions/chunk — comfortably inside
 * the proven-safe range with real headroom, without so many chunks that
 * per-paper API call count (and latency/cost) balloons unnecessarily.
 */
export const DEFAULT_PAGES_PER_CHUNK = 8;

/**
 * A 1-page overlap between consecutive chunks is the minimum needed to
 * guarantee that a question whose text is split exactly at a page boundary
 * still appears whole in at least one chunk (the one that gained the
 * overlapped page) instead of being cut in half in both. The unavoidable
 * cost is that the overlapped page's content — and so, typically, its
 * question(s) — gets independently generated by both chunks; `dedupeQuestions`
 * exists specifically to collapse that back down to one row.
 */
export const DEFAULT_OVERLAP_PAGES = 1;

export interface ChunkingOptions {
  pagesPerChunk?: number;
  overlapPages?: number;
}

function renderPages(pages: ExtractedPage[]): string {
  return pages.map((p) => `${p.text}\n-- ${p.num} of ${p.total} --`).join('\n\n');
}

/**
 * Splits `extractedText` into a page-boundary-aware, overlapping sequence
 * of chunk strings, each meant to be sent to an AI provider as its own
 * `generateQuizFromPaper` sub-call. A paper that already fits in one chunk
 * is returned completely unchanged as a single-element array — byte-for-byte
 * identical to the pre-TAPS-4.5 single-call behavior, so nothing about a
 * short paper's generation call changes.
 */
export function chunkPastPaperText(extractedText: string, options: ChunkingOptions = {}): string[] {
  const pagesPerChunk = options.pagesPerChunk ?? DEFAULT_PAGES_PER_CHUNK;
  const overlapPages = options.overlapPages ?? DEFAULT_OVERLAP_PAGES;
  const pages = splitIntoPages(extractedText);

  if (pages.length <= pagesPerChunk) {
    return [extractedText];
  }

  const step = Math.max(1, pagesPerChunk - overlapPages);
  const chunks: string[] = [];
  let start = 0;
  while (start < pages.length) {
    const end = Math.min(start + pagesPerChunk, pages.length);
    chunks.push(renderPages(pages.slice(start, end)));
    if (end >= pages.length) break;
    start += step;
  }
  return chunks;
}

/**
 * Collapses duplicate questions produced when the same source content
 * appears in more than one chunk (the overlap `chunkPastPaperText`
 * deliberately introduces at chunk boundaries — see `DEFAULT_OVERLAP_PAGES`).
 * Two questions are treated as the same one if their question text is
 * identical after trimming, collapsing internal whitespace, and
 * case-folding: the model is instructed to extract questions verbatim from
 * the source text ("do not invent questions that are not actually in the
 * source text"), so an overlapped page's question(s) should come back
 * near-byte-identical from both chunks that saw it, not just semantically
 * similar — exact normalized-text matching is intentionally simple rather
 * than fuzzy, and keeps the *first* occurrence (from the earlier chunk).
 */
export function dedupeQuestions<T extends { question: { question: string } }>(items: T[]): T[] {
  const seen = new Set<string>();
  const result: T[] = [];
  for (const item of items) {
    const key = normalizeQuestionText(item.question.question);
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(item);
  }
  return result;
}

function normalizeQuestionText(text: string): string {
  return text.trim().toLowerCase().replace(/\s+/g, ' ');
}
