-- TAPS-4.0: PastPaper text-extraction pipeline state. Written by hand rather
-- than `prisma migrate dev`'s raw diff output: this schema's `searchVector`
-- columns (ExamBoard/Post) are Postgres generated columns modeled in
-- schema.prisma as `Unsupported("tsvector")` (see docs/adr/009-full-text-
-- search.md), and Prisma's diff engine doesn't know how to represent them,
-- so an autogenerated diff against this schema spuriously tries to
-- `ALTER COLUMN ... DROP DEFAULT` on those columns and drop their indexes —
-- neither of which has anything to do with this migration's actual change.
-- This file contains only the real change: the new `ExtractionStatus` enum
-- and `PastPaper.extractedText` / `PastPaper.extractionStatus` columns.

-- CreateEnum
CREATE TYPE "ExtractionStatus" AS ENUM ('PENDING', 'DONE', 'FAILED');

-- AlterTable
ALTER TABLE "past_papers"
  ADD COLUMN "extractedText" TEXT,
  ADD COLUMN "extractionStatus" "ExtractionStatus" NOT NULL DEFAULT 'PENDING';
